# Generated by Django 4.1.6 on 2023-02-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('is_crypto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_15_minutes_ago', models.FloatField(default=None, null=True)),
                ('value_now', models.FloatField(default=None, null=True)),
                ('buy', models.FloatField(default=None, null=True)),
                ('sell', models.FloatField(default=None, null=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points_from', to='data_collection.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points_to', to='data_collection.currency')),
            ],
        ),
    ]
