# Generated by Django 4.1.6 on 2023-02-07 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepoint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
