# Generated by Django 4.1.6 on 2023-02-07 11:08

import data_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_alter_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepoint',
            name='collection_id',
            field=models.TextField(default=data_collection.models.current_uuid),
        ),
    ]
